version: "3.8"
services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "5000:5000"
    env_file: .env

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "3000:80"
